stages:
  - build
  - test
  - package
  - publish

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$ll-unidade

# Cacheia dependências e plugins já baixados durante builds (utilizando o diretório salvo em MAVEN_OPTS)
cache:
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3-eclipse-temurin-20-alpine
  script:
    - mvn $MAVEN_OPTS compile
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "main"

test:
  stage: test
  image: maven:3-eclipse-temurin-20-alpine
  script:
    - mvn $MAVEN_OPTS test
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "main"

package:
  stage: package
  image: maven:3-eclipse-temurin-20-alpine
  script:
    - mvn $MAVEN_OPTS package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "main"

publish:
  stage: publish
  image: docker:24
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "main"
